"""
Example usage of map_multiple_vector_files with all available basemap providers.

For every provider, one map of the Qinghai Lake study area is produced.
Layers are drawn in the following order (bottom -> top):
1. the basemap tiles of the provider
2. the lake boundary polygon (in between, filled)
3. the latlon mesh cells (on top, outline only)
"""

import os

import numpy as np

import matplotlib
matplotlib.use('Agg')  # headless rendering: avoids TkAgg crash when creating many figures in a loop
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from osgeo import osr

from pyearthviz.map.raster_map_servers import RasterTileServer
from pyearthviz.map.vector.map_multiple_vector_files import map_multiple_vector_files
from pyearth.gis.gdal.read.vector.gdal_get_vector_boundary import gdal_get_vector_boundary
from pyearth.gis.gdal.read.vector.gdal_get_vector_extent import gdal_get_vector_extent

# ============================================================
# Qinghai Lake configuration
# ============================================================


sFilename_basin_boundary = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'qinghaihu', 'basin_boundary_qinghaihu.geojson')
sFilename_lake_boundary = os.path.join(os.path.dirname(__file__), '..', '..', 'data','qinghaihu', 'lake_boundary_qinghaihu.geojson')
##convert to absolute path
sFilename_basin_boundary = os.path.abspath(sFilename_basin_boundary)
print(f"Boundary file: {sFilename_basin_boundary}")
aExtent = gdal_get_vector_extent(sFilename_basin_boundary)
print(f"Boundary extent: {aExtent}")

# latlon mesh generated by examples/latlon/example_create_lanlon.py
sWorkspace_project = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sFilename_mesh = os.path.join(sWorkspace_project, 'data', 'qinghaihu', 'lake_latlon.geojson')
sWorkspace_output = os.path.join(sWorkspace_project, 'data', 'qinghaihu')



# compute the zoom level that matches a 1000x1000 pixel figure at 150 dpi
image_size = [1000, 1000]
dpi = 150
scale_denominator = RasterTileServer.calculate_scale_denominator(aExtent, image_size)
pSrc = osr.SpatialReference()
pSrc.ImportFromEPSG(3857)  # mercator
pProjection = pSrc.ExportToWkt()
iZoom_level = RasterTileServer.calculate_zoom_level(scale_denominator, pProjection, dpi=dpi)
print(f'Computed zoom level for Qinghai Lake: {iZoom_level}')


def example_map_all_providers():
    """Map the lake boundary and the mesh on top of every basemap provider, one by one."""
    print("=" * 60)
    print("Example: Map all basemap providers one by one")
    print("=" * 60)

    if not os.path.exists(sFilename_mesh):
        print(f"Mesh file not found: {sFilename_mesh}")
        print("Run examples/latlon/example_create_lanlon.py first")
        return

    # cartopy built-in OSM plus every provider in the registry
    aProvider = ['OSM'] + RasterTileServer.get_available_providers()
    print(f"Mapping {len(aProvider)} providers: {', '.join(aProvider)}")

    dLon_center = 0.5 * (aExtent[0] + aExtent[1])
    dLat_center = 0.5 * (aExtent[2] + aExtent[3])

    for sProvider in aProvider:
        
        iZoom_provider = iZoom_level
        if sProvider != 'Esri.NatGeo':
            continue       

        sFilename_output = os.path.join(sWorkspace_output, f'lake_latlon_map_{sProvider}.png')
        print(f"Mapping provider: {sProvider}")
        try:
            map_multiple_vector_files(
                [3, 3, 3],  # polygon, polygon
                [sFilename_basin_boundary, sFilename_lake_boundary, sFilename_mesh],  # lake boundary in between, mesh on top
                aFlag_fill_in=[0, 1, 0],  # lake filled, mesh outline only
                aColor_in=['black','red', 'blue'],
                aThickness_in=[1.0,1.0, 0.5],
                aBasemap_provider_in=[sProvider],
                iBasemap_zoom_level_in=iZoom_provider,
                aExtent_in=aExtent,
                iFlag_zebra_in= 1,
                #pProjection_map_in=ccrs.PlateCarree(),  # avoid the default Orthographic projection, whose GEOS limb-clipping can crash silently
                iFlag_title_in=1,
                sTitle_in=f'Qinghai Lake - {sProvider}',
                iDPI_in=dpi,
                sFilename_output_in=sFilename_output,
            )
        except Exception as e:
            print(f"Error with {sProvider}: {e}")
            plt.close('all')
    print()


def main():
    """Run all examples."""
    print("\n" + "=" * 60)
    print("map_multiple_vector_files Examples - Qinghai Lake")
    print("=" * 60 + "\n")

    example_map_all_providers()

    print("=" * 60)
    print("All examples completed!")
    print(f"Check the output folder: {sWorkspace_output}")
    print("=" * 60)


if __name__ == '__main__':
    main()
